config/routes.rb
Rails.application.routes.draw do
  devise_for :users#, controllers: { sessions: 'users/sessions' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # delete '/users/sign_out', to: 'application#sign_out_user', as: :destroy_user_session
  # devise_scope :user do
  #   delete '/users/sign_out', to: 'devise/sessions#destroy'
  # end

  delete '/users/sign_out', to: 'users#sign_out_user', as: :sign_out_user

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :users, only: [:index, :show]
  resources :posts do
    get 'edit', on: :member
    post '/like', to: 'likes#create', as: :like_post
    resources :comments
  end
  resources :tags

  get 'my_posts', to: 'posts#my_posts', as: 'my_posts'
  get '/users/:user_id/posts/:id/custom_edit', to: 'posts#edit', as: 'custom_edit_user_post'
  get '/search', to: 'search#index', as: 'search'

  root "application#home"
end

app/views/shared/_flash.html.erb
<% if flash.now[:alert].present? %>
  <div class="flash">
    <%= flash.now[:alert] %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_path %>">ProsePal</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/posts/new">New Post</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= my_posts_path %>">My Posts</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= user_path(current_user) %>">My Profile</a>
          </li>
        <% end %>
        <li>
          <a class="nav-link" href="/posts">All Posts</a>
        </li>
        <li>
          <a class="nav-link" href="/tags">All Tags</a>
        </li>
        <li>
          <a class="nav-link" href="/users">All Users</a>
        </li>

      </ul>
      <form class="d-flex" method="GET" action="<%= search_path %>">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="query">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>