config/routes.rb
Rails.application.routes.draw do
  devise_for :users#, controllers: { sessions: 'users/sessions' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # delete '/users/sign_out', to: 'application#sign_out_user', as: :destroy_user_session
  # devise_scope :user do
  #   delete '/users/sign_out', to: 'devise/sessions#destroy'
  # end

  delete '/users/sign_out', to: 'users#sign_out_user', as: :sign_out_user

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :users, only: [:index, :show]
  resources :posts do
    get 'edit', on: :member
    post '/like', to: 'likes#create', as: :like_post
    resources :comments
  end
  resources :tags

  get 'my_posts', to: 'posts#my_posts', as: 'my_posts'
  get '/users/:user_id/posts/:id/custom_edit', to: 'posts#edit', as: 'custom_edit_user_post'
  get '/search', to: 'search#index', as: 'search'

  root "application#home"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :posts_tags, dependent: :destroy
  has_many :tags, through: :posts_tags

  accepts_nested_attributes_for :tags, reject_if: :all_blank, allow_destroy: true

  # attr_accessor :tag_list

  # after_save :assign_tags

  validates :text, length: { in: 10..500 }
  validates :title, length: { in: 5..30 }

  def self.search(query)
    joins(:tags, :comments).where("posts.title LIKE ? OR posts.text LIKE ? OR tags.name LIKE ? OR comments.text LIKE ?", "%#{query}%", "%#{query}%", "%#{query}%", "%#{query}%").distinct
  end

  def increment_likes_counter
    self.likes_counter += 1
    save
  end

  def increment_comments_counter
    self.comments_counter += 1
    save
  end

  def tag_list=(tags_string_or_array)
    if tags_string_or_array.is_a?(String)
      tag_names = tags_string_or_array.split(",").collect(&:strip).map(&:downcase).uniq
    elsif tags_string_or_array.is_a?(Array)
      tag_names = tags_string_or_array.map(&:strip).map(&:downcase).uniq
    end

    self.tags = tag_names.map { |name| Tag.find_or_initialize_by(name: name) }
  end

  # private

  # def assign_tags(tag_names)
  #   tag_names.each do |name|
  #     tag = Tag.find_or_create_by(name: name)
  #     self.tags << tag
  #   end
  # end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_user, except: [:index]
  before_action :set_post, except: [:index, :new, :create, :my_posts]
  before_action :authenticate_user!, except: [:index, :show]
  # skip_after_action :turbostream

  def index
    @posts = Post.order(created_at: :desc)
  end

  def show
    @like = current_user.likes.find_by(post_id: @post.id) || Like.new
    @comments = @post.comments
    @new_comment = @post.comments.new
    @post_comments = @post.comments.includes(:user)
  end

  def new
    @post = Post.new
    @post.tags.build
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    # Parse the tag_list manually before saving
    tag_list = params[:post][:tag_list].split(",").map(&:strip)
    @post.tag_list = tag_list

    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def edit
    if @post.user == current_user
      render :edit
    else
      redirect_to @post, alert: "You are not authorized to edit this post."
    end
  end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy
    redirect_to user_posts_path(@user)
  end

  def my_posts
    @posts = current_user.posts.order(created_at: :desc)
  end

  private

  def set_user
    @user = params[:user_id] ? User.find(params[:user_id]) : current_user
  end

  def set_post
    @post = Post.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The post you're looking for doesn't exist."
    redirect_to posts_path # Redirect to the index page for posts
  end

  def post_params
    params.require(:post).permit(:title, :text, :tag_list)
  end

  def authenticate_user!
    unless user_signed_in?
      flash[:alert] = "You must be signed in to perform this action."
      redirect_to new_user_session_path
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  include Rails.application.routes.url_helpers

  # def post_params
  #   params.require(:post).permit(:title, :text, :tag_list)
  # end
end

app/views/posts/_form.html.erb
<%= form_for @post, html: {multipart: true, data: { turbo: false }} do |form| %>

  <% if @post.errors.any? %>
    <div>
      <% @post.errors.full_messages.each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  <% end %>

  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>

<div>
  <%= form.label :tag_list, "Tags (comma-separated)" %>
  <%= form.text_field :tag_list, value: @post.tags&.pluck(:name)&.join(', ') %>
</div>


  <%= form.submit %>
<% end %>

app/views/posts/create.js.erb
<%# 
const postsContainer = document.getElementById("posts-container");

postsContainer.insertAdjacentHTML("beforeend", "<%= turbo_stream.replace @post %>"); %>

app/views/posts/create.turbo_stream.erb
<%# <turbo-stream action="append" target="posts-container">
  <template>
    <%= render partial: 'post', locals: { post: @post } %>
  <%# </template>
</turbo-stream> %> %>

app/views/posts/edit.html.erb
<h1>Edit post</h1>

<%= render partial: 'form', locals: { user: @user, post: @post } %>
<%= button_to "delete post", post_path(@post), method: :delete, data: { turbo_confirm: "Are you sure?" } %>

app/views/posts/index.html.erb
<h1>All posts</h1>

<% @posts.each do |post| %>
  <div>
    <h2><%= link_to post.title, post_path(post) %></h2>
    <p>by <%= link_to post.user.username, user_path(post.user) %></p>
    <p><%= truncate(post.text, length: 20) %></p>
    <p>Created <%= time_ago_in_words(post.created_at) %> ago...</p>
  </div>
<% end %>

<!-- Define a Turbo Stream to handle updates -->
<turbo-stream action="append" target="posts-container">
  <template>
    <%# Pass the post as a parameter to the template %>
    <%# This template will be used to append new posts to the list %>
    <%# Use post as the local variable in the loop %>
    <% @posts.each do |post| %>
      <div>
        <h2><%= link_to post.title, post_path(post) %></h2>
        <p>by <%= link_to post.user.username, user_path(post.user) %></p>
        <p><%= truncate(post.text, length: 20) %></p>
        <p>Created <%= time_ago_in_words(post.created_at) %> ago...</p>
      </div>
    <% end %>
  </template>
</turbo-stream>

<div id="posts-container" data-controller="posts">
  <turbo-frame id="new-post-frame" src="/posts"></turbo-frame>
</div>

app/views/posts/my_posts.html.erb
<h1>My posts!</h1>

<% @posts.each do |post| %>
  <div>
    <h2><%= link_to post.title, post_path(post) %></h2>
    <p><%= truncate(post.text, length: 20) %></p>
    <p>Created <%= post.created_at.strftime("%d %B %Y, %H:%M") %></p>
    <p>Last updated <%= post.updated_at.strftime("%d %B %Y, %H:%M") %></p>
  </div>
<% end %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render partial: 'form', locals: { user: @user, post: @post } %>

app/views/posts/show.html.erb
<% if flash[:alert].present? %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>

<h1><%= @post.title %></h1>
<p>
  <% if @post.created_at.present? %>
    Created <%= time_ago_in_words(@post.created_at) %> ago...
  <% else %>
    Created recently...
  <% end %>
</p>
<p>By <%= link_to @post.user.username, user_path(@post.user) %></p>
<p><%= @post.text %></p>
<p>
  Tags:
  <% @post.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag) %>
  <% end %>
</p>

<p>Last updated <%= @post.updated_at.strftime("%d %B %Y, %H:%M") %></p>

<% if @like.persisted? %>
  <p>You liked this post.</p>
<% else %>
  <%= form_with model: @like, url: post_like_post_path(@post), method: :post do |form| %>
    <%= form.submit 'Like post', class: 'submit' %>
  <% end %>
<% end %>

<p>Likes: <%= @post.likes_counter || 0 %> </p>
<p>Comments: <%= @post.comments_counter || 0 %> </p>

<% if @post_comments.any? %>
  <ul>
    <% @post_comments.each do |comment| %>
      <li>
        <%= comment.user&.username %> <%= comment.created_at&.strftime("%d %B %Y, %H:%M") %>: <%= comment.text %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>There are no comments... yet</p>
<% end %>

<%= form_with(model: @new_comment, url: post_comments_path(@post)) do |form| %>
  <%= form.text_area :text, placeholder: "Enter your comment here..." %>
  <%= form.submit "Post Comment" %>
<% end %>

<% if user_signed_in? && @post.user == current_user %>
  <%= link_to "edit post", edit_post_path(@post) %>
<% end %>