config/routes.rb
Rails.application.routes.draw do
  devise_for :users#, controllers: { sessions: 'users/sessions' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # delete '/users/sign_out', to: 'application#sign_out_user', as: :destroy_user_session
  # devise_scope :user do
  #   delete '/users/sign_out', to: 'devise/sessions#destroy'
  # end

  delete '/users/sign_out', to: 'users#sign_out_user', as: :sign_out_user

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :users, only: [:index, :show]
  resources :posts do
    get 'edit', on: :member
    post '/like', to: 'likes#create', as: :like_post
    resources :comments
  end
  resources :tags

  get 'my_posts', to: 'posts#my_posts', as: 'my_posts'
  get '/users/:user_id/posts/:id/custom_edit', to: 'posts#edit', as: 'custom_edit_user_post'
  get '/search', to: 'search#index', as: 'search'

  root "application#home"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProsePal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'application', 'data-turbo-track': 'reload' %>
    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css' %>

  </head>

  <body>

  <header>
    <%= render partial: "shared/navbar" %>
  </header>
    <%= render partial: 'shared/flash' %>

    <%= yield %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/home.html.erb
<% if @user.nil? %>
  <h1>Hello!</h1>
  <h2>Please log in or sign up to use the site</h2>

  <%= link_to "log in", new_user_session_path %>
  <%= link_to "sign up", new_user_registration_path %>

<% else %>
  <h1>Hey, <%= @user.first_name %>!</h1>

  <%= link_to "edit profile", edit_user_registration_path %>
  <%= link_to "Sign out", sign_out_user_path, method: :delete %>
  <%= link_to "new post", new_post_path %>
  <%= link_to "my posts", my_posts_path %>
  <%= link_to "all posts", posts_path %>
  <%= link_to "all users", users_path %>
  <%= link_to "all tags", tags_path %>

<% end %>